// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Home = require("./Home.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function app() {
  return ReasonReact.element(undefined, undefined, Home.make("Passed", /* array */[]));
}

exports.app = app;
/* Home Not a pure module */
